# fly.toml app configuration file generated for uzi-quiz on 2024-02-23T11:42:17-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'uzi-quiz'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
